#!/bin/bash
# Script made to take screenshots

SCREENSHOTS_FOLDER="${HOME}/Pictures/screenshots"

if ! [ -d $SCREENSHOTS_FOLDER ]; then
    mkdir -p $SCREENSHOTS_FOLDER
fi
TIMESTAMP=`date +%Y%m%d_%H%M%S`
idx=0
output_file=''
while [ -z $output_file ]; do
    filename=${TIMESTAMP}_${idx}.png
    if [ -f "$SCREENSHOTS_FOLDER/$filename" ]; then
        idx=$idx+1
    else
        output_file="$SCREENSHOTS_FOLDER/$filename"
    fi
done
import -window root ${output_file}
